# Generated by Django 4.2 on 2025-04-10 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='권 이름')),
                ('abbreviation', models.CharField(max_length=10, verbose_name='약어')),
            ],
            options={
                'verbose_name': '성경 권',
                'verbose_name_plural': '성경 권들',
            },
        ),
        migrations.CreateModel(
            name='Testament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='구분 이름')),
            ],
            options={
                'verbose_name': '성경 구분',
                'verbose_name_plural': '성경 구분들',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='번역본 이름')),
                ('language', models.CharField(max_length=50, verbose_name='언어')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
            ],
            options={
                'verbose_name': '성경 번역본',
                'verbose_name_plural': '성경 번역본들',
            },
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.IntegerField(verbose_name='장 번호')),
                ('number', models.IntegerField(verbose_name='절 번호')),
                ('content', models.TextField(verbose_name='내용')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='bible.book', verbose_name='권')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='bible.version', verbose_name='번역본')),
            ],
            options={
                'verbose_name': '성경 절',
                'verbose_name_plural': '성경 절들',
                'ordering': ['version', 'book', 'chapter', 'number'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='testament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='bible.testament', verbose_name='구분'),
        ),
    ]
