# Generated by Django 4.2 on 2025-04-10 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='books',
        ),
        migrations.AlterModelTable(
            name='testament',
            table='testaments',
        ),
        migrations.AlterModelTable(
            name='verse',
            table='verses',
        ),
        migrations.AlterModelTable(
            name='version',
            table='versions',
        ),
    ]
