# Generated by Django 4.2 on 2025-04-10 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0002_alter_book_table_alter_testament_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table=None,
        ),
        migrations.AlterModelTable(
            name='testament',
            table=None,
        ),
        migrations.AlterModelTable(
            name='verse',
            table=None,
        ),
        migrations.AlterModelTable(
            name='version',
            table=None,
        ),
    ]
